git clone https://git-iut.univ-lille1.fr/aitelhaa/webRiche AIT_ELHAJ_Azzedine   
git clone https://git-iut.univ-lille1.fr/belsa/M4103C.git BELS_Alexis          
git clone https://git-iut.univ-lille1.fr/beunsv/m4103c-javascript BEUNS_Vianney        
git clone https://git-iut.univ-lille1.fr/cantac/M4103C.git CANTA_Carmelo        
git clone https://git-iut.univ-lille1.fr/choukhis/ClientRiche CHOUKHI_Sofian       
git clone https://framagit.org/Dosto/javascript COLLOT_Louis-Arthur  
git clone https://git-iut.univ-lille1.fr/devassia/java_script_iut_info_s4.git DEVASSINE_Alexandre  
git clone https://git-iut.univ-lille1.fr/duquesnr/M4103C.git DUQUESNE_Romain      
git clone https://git-iut.univ-lille1.fr/gerardc/ProgWeb GERARD_Cyril         
git clone https://gitlab.com/Flyxe/JavaScript.git HOURDEAU_Antoine     
git clone https://framagit.org/Wardow/JavasKrypt JEDRZEJAK_William    
git clone https://git-iut.univ-lille1.fr/laffileh/javascript LAFFILÉ_Hugo         
git clone https://git-iut.univ-lille1.fr/mayeuxw/TpJavaScript MAYEUX_William       
git clone https://git-iut.univ-lille1.fr/pelleria/loveandjavascript PELLERIN_Alexandre   
git clone https://git-iut.univ-lille1.fr/plouvinm/webClient PLOUVIN_Margot       
git clone https://git-iut.univ-lille1.fr/regnierk/Tps_JavaS.git REGNIER_Kévin        
git clone https://git-iut.univ-lille1.fr/tihiania/M4103C TIHIANINE_Adel       
git clone https://git-iut.univ-lille1.fr/vanrenta/JavaScript VANRENTERGHEM_Anthony 
git clone https://git-iut.univ-lille1.fr/vasseurs/TP1-JS VASSEUR_Samson       
