rm -rf target && mkdir target
git clone https://git-iut.univ-lille1.fr/aitelhaa/webRiche                    target/AIT_ELHAJ_Azzedine
git clone https://git-iut.univ-lille1.fr/belsa/M4103C.git                     target/BELS_Alexis          
git clone https://git-iut.univ-lille1.fr/beunsv/m4103c-javascript             target/BEUNS_Vianney        
git clone git@gitlab.com:_Blaoi/JS-IUT.git                                    target/BOREE_Cyprien
git clone https://git-iut.univ-lille1.fr/cantac/M4103C.git                    target/CANTA_Carmelo        
git clone https://git-iut.univ-lille1.fr/choukhis/ClientRiche                 target/CHOUKHI_Sofian       
git clone git@framagit.org:Dosto/javascript.git                               target/COLLOT_Louis-Arthur  
git clone https://git-iut.univ-lille1.fr/devassia/java_script_iut_info_s4.git target/DEVASSINE_Alexandre  
git clone https://git-iut.univ-lille1.fr/duquesnr/M4103C.git                  target/DUQUESNE_Romain      
git clone https://git-iut.univ-lille1.fr/gerardc/ProgWeb                      target/GERARD_Cyril         
git clone git@gitlab.com:Flyxe/JavaScript.git                                 target/HOURDEAU_Antoine     
git clone git@framagit.org:Wardow/JavasKrypt.git                              target/JEDRZEJAK_William    
git clone https://git-iut.univ-lille1.fr/laffileh/javascript                  target/LAFFILÉ_Hugo         
git clone https://git-iut.univ-lille1.fr/mayeuxw/TpJavaScript                 target/MAYEUX_William       
git clone https://git-iut.univ-lille1.fr/pelleria/loveandjavascript           target/PELLERIN_Alexandre   
#git clone                                                                    target/ PICAULT_Maxime
git clone https://git-iut.univ-lille1.fr/plouvinm/webClient                   target/PLOUVIN_Margot       
git clone https://git-iut.univ-lille1.fr/regnierk/Tps_JavaS.git               target/REGNIER_Kévin        
git clone https://git-iut.univ-lille1.fr/tihiania/M4103C                      target/TIHIANINE_Adel       
git clone https://git-iut.univ-lille1.fr/vanrenta/JavaScript                  target/VANRENTERGHEM_Anthony 
git clone https://git-iut.univ-lille1.fr/vasseurs/TP1-JS                      target/VASSEUR_Samson       
